### ISSUE TITLE
token 

### ISSUE THREAD

**Issue by Bananawhat02** [vastus/node-hcaptcha#17]
hello,What is token from widget ? And how to get it ?

**Comment by Keith12127** [comment]
> hello,What is token from widget ? And how to get it ?

**Comment by Syaamilmaulana256** [comment]
Itu mungkin dari hcaptcha.com
Dan didapatkan dari akun kalian




Wong jowo yo kudu ngerti
Yokpo cara ne

**Comment by Syaamilmaulana256** [comment]
Kontol bapakmu cilik 🤣🤣🤣
