### ISSUE TITLE
index.d.ts type discrepancy

### ISSUE THREAD

**Issue by tilkinsc** [vastus/node-hcaptcha#24]
https://docs.hcaptcha.com/

According to hcaptcha's developer guide, there are fields score and score_reason, which aren't taken into account in the types declaration.

{
   "success": true|false,     // is the passcode valid, and does it meet security criteria you specified, e.g. sitekey?
   "challenge_ts": timestamp, // timestamp of the challenge (ISO format yyyy-MM-dd'T'HH:mm:ssZZ)
   "hostname": string,        // the hostname of the site where the challenge was solved
   "credit": true|false,      // optional: deprecated field
   "error-codes": [...]       // optional: any error codes
   "score": float,            // ENTERPRISE feature: a score denoting malicious activity.
   "score_reason": [...]      // ENTERPRISE feature: reason(s) for score.
}

**Comment by Maksymalnie** [comment]
Jij

**Comment by Maksymalnie** [comment]
Thursday's breaking news
🗞️📰📰📰📰📰📰📰

News Type : Initial Jobless Claims
Currency : USD🇺🇸
Time : 17:30  
Effects : ⭐
Previously : 229K
Forecast : 225K
———————————————

News Type : PPI (MoM) (May)
Currency : USD🇺🇸
Time : 17:30
Effects : ⭐
Previously : 0.5%  
Forecast : 0.1%  
———————————————

News Type : Core PPI m/m
Currency : USD🇺🇸
Time : 17:30
Effects : ⭐
Previously : 0.5%  
Forecast : 0.3%  
———————————————


PAKISTAN Time Zone 

Subscribe to https://t.me/+KcCkfhl7PipmN2M0

**Comment by Maksymalnie** [comment]
Thursday's breaking news
🗞️📰📰📰📰📰📰📰

News Type : Initial Jobless Claims
Currency : USD🇺🇸
Time : 17:30  
Effects : ⭐
Previously : 229K
Forecast : 225K
———————————————

News Type : PPI (MoM) (May)
Currency : USD🇺🇸
Time : 17:30
Effects : ⭐
Previously : 0.5%  
Forecast : 0.1%  
———————————————

News Type : Core PPI m/m
Currency : USD🇺🇸
Time : 17:30
Effects : ⭐
Previously : 0.5%  
Forecast : 0.3%  
———————————————


PAKISTAN Time Zone 

Subscribe to https://t.me/+KcCkfhl7PipmN2M0
